#define _POSIX_C_SOURCE 199309L
#include <stdio.h>
#include <stdlib.h>
#include <ncurses.h>
#include <time.h>

char* grid;

struct timespec req, rem;

int row;
int col;
int* row_p = &row;
int* col_p = &col;
size_t itms;

void output(){
        for (int x=0; x<row; x++){
                mvaddnstr(x, 0, &grid[x * col], col);
        }
        refresh();
}

void output_bin(FILE* fptr, int moveby){
        fseek(fptr, moveby, SEEK_CUR);
        itms = fread(grid, col*row, 1, fptr);
        if (itms != 1){ perror("Error reading file");}
        output();
}

int main(int argc, char* argv[]){
        if (argc <= 1 || argc >3){
                printf("View recording generated by fracterm\n\n"
                       "cinematograph [file path] <fps>\n"
                       "<fps> | An integer in range 4-48\n"
                       "        [24: default]\n\n"
                       "In window:\n"
                       "a/d: forward/backward\n"
                       "q  : quit\n");
                return 0;
        }
        if (argc == 3){
                long fps = atol(argv[2]);
                if (fps < 4)  {fps = 4;}
                if (fps > 48) {fps = 48;}
                req.tv_sec = 0;
                req.tv_nsec = 1000000000L/fps;
        }
        else {
                req.tv_sec = 0;
                req.tv_nsec = 1000000000L/24;
        }

        FILE *fptr;
        fptr = fopen(argv[1], "rb");
        if (fptr == NULL) {
                printf("Could not open file/file DNE\n");
                return 0;
        }
        fseek(fptr, 0L, SEEK_END);
        int sz = ftell(fptr);
        rewind(fptr);

        //fetch dimensions
        itms = fread(row_p, sizeof(int), 1, fptr);
        if (itms != 1){ perror("Error reading file");}
        itms = fread(col_p, sizeof(int), 1, fptr);
        if (itms != 1){ perror("Error reading file");}

        grid = (char*) malloc(row*col);
        int moveby = row*col;

        initscr();
        raw();
        noecho();
        keypad(stdscr, FALSE);
        //cbreak();
        timeout(100);
        char ch;

        itms = fread(grid, col*row, 1, fptr);
        if (itms != 1){ perror("Error reading file");}
        output();
        while ((ch = getch()) != 'q'){
                if (ch=='a'){
                        if (ftell(fptr)+moveby < sz){
                                output_bin(fptr, 0);
                        }
                        nanosleep(&req, NULL);
                }
                if (ch=='d'){
                        if (ftell(fptr)-moveby > 0){
                                output_bin(fptr, (-2)*moveby);
                        }
                        nanosleep(&req, NULL);
                }

        }

        free(grid);
        fclose(fptr);
        refresh();
        endwin();
        return 0;
}
